// <auto-generated />
using HairDressersWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HairDressersWeb.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20221216124907_Seeding2")]
    partial class Seeding2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("HairDressersWeb.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HairDressersWeb.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterSurname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            MasterSurname = "Hanyk",
                            Type = 0
                        },
                        new
                        {
                            Id = 1,
                            MasterSurname = "Vaskiv",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            MasterSurname = "Rudnyk",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            MasterSurname = "Dutka",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            MasterSurname = "Khalus",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
